"""
Phase 5 — Health Assessment Report
Generates a structured PDF report from all pipeline phases.
"""

import io
import json
import datetime
import numpy as np
import cv2
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, Image as RLImage
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics import renderPDF


# ─── Color palette ────────────────────────────────────────────────────────────
C_DARK   = colors.HexColor("#1A1F2E")
C_ACCENT = colors.HexColor("#2D7DD2")
C_LIGHT  = colors.HexColor("#F4F7FC")
C_GREEN  = colors.HexColor("#28A745")
C_YELLOW = colors.HexColor("#FFC107")
C_ORANGE = colors.HexColor("#FD7E14")
C_RED    = colors.HexColor("#DC3545")
C_GRAY   = colors.HexColor("#6C757D")
C_WHITE  = colors.white


def _sev_color(severity_str: str):
    s = severity_str.lower()
    if s == "none":   return C_GREEN
    if s == "mild":   return C_YELLOW
    if s == "moderate": return C_ORANGE
    if s == "notable":  return C_RED
    return C_GRAY


# ─── Report generator ─────────────────────────────────────────────────────────

class ReportGenerator:

    PAGE_W, PAGE_H = A4
    MARGIN = 20 * mm

    def generate(self,
                 phase1, phase2, phase3, phase4,
                 annotated_image_bgr=None,
                 patient_id: str = "UNKNOWN",
                 output_path: str = None) -> bytes:
        """
        Generate PDF report.
        Returns PDF bytes; also saves to output_path if given.
        """
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=self.MARGIN,
            rightMargin=self.MARGIN,
            topMargin=self.MARGIN,
            bottomMargin=self.MARGIN,
        )

        styles = self._make_styles()
        story  = []

        # ── Header ────────────────────────────────────────────────────────────
        story += self._header(styles, patient_id)
        story.append(Spacer(1, 4*mm))
        story.append(HRFlowable(width="100%", thickness=2, color=C_ACCENT))
        story.append(Spacer(1, 4*mm))

        # ── Annotated image ───────────────────────────────────────────────────
        if annotated_image_bgr is not None:
            story += self._image_section(annotated_image_bgr, styles)
            story.append(Spacer(1, 4*mm))

        # ── Section 1: Face Overview ──────────────────────────────────────────
        story += self._face_overview_section(phase1, phase4.face, styles)

        # ── Section 2: Eye Analysis ───────────────────────────────────────────
        story += self._eye_section(phase3, phase4.eyes, styles)

        # ── Section 3: Skin Analysis ──────────────────────────────────────────
        story += self._skin_section(phase3, phase4.skin, styles)

        # ── Section 4: Lip Analysis ───────────────────────────────────────────
        story += self._lip_section(phase3, phase4.lips, styles)

        # ── Section 5: Overall Assessment ────────────────────────────────────
        story += self._overall_section(phase4, styles)

        # ── Footer disclaimer ─────────────────────────────────────────────────
        story.append(Spacer(1, 6*mm))
        story.append(HRFlowable(width="100%", thickness=1, color=C_GRAY))
        story.append(Spacer(1, 2*mm))
        story.append(Paragraph(
            "⚠ DISCLAIMER: This report is generated by an automated computer vision system "
            "and contains visual observations only. It does NOT constitute a medical diagnosis, "
            "clinical assessment, or treatment recommendation. Always consult a qualified "
            "healthcare professional regarding any health concerns.",
            styles["disclaimer"]
        ))

        doc.build(story)
        pdf_bytes = buf.getvalue()

        if output_path:
            Path(output_path).write_bytes(pdf_bytes)

        return pdf_bytes

    # ── styles ────────────────────────────────────────────────────────────────

    def _make_styles(self):
        base = getSampleStyleSheet()
        s = {}

        s["title"] = ParagraphStyle("title",
            fontName="Helvetica-Bold", fontSize=20, textColor=C_DARK,
            alignment=TA_LEFT, spaceAfter=2*mm)

        s["subtitle"] = ParagraphStyle("subtitle",
            fontName="Helvetica", fontSize=10, textColor=C_GRAY,
            alignment=TA_LEFT, spaceAfter=1*mm)

        s["section_head"] = ParagraphStyle("section_head",
            fontName="Helvetica-Bold", fontSize=13, textColor=C_ACCENT,
            spaceBefore=5*mm, spaceAfter=2*mm)

        s["sub_head"] = ParagraphStyle("sub_head",
            fontName="Helvetica-Bold", fontSize=10, textColor=C_DARK,
            spaceBefore=2*mm, spaceAfter=1*mm)

        s["body"] = ParagraphStyle("body",
            fontName="Helvetica", fontSize=9, textColor=C_DARK,
            leading=13, spaceAfter=1*mm)

        s["obs_normal"] = ParagraphStyle("obs_normal",
            fontName="Helvetica", fontSize=9, textColor=colors.HexColor("#2E7D32"),
            leading=12, leftIndent=4*mm)

        s["obs_mild"] = ParagraphStyle("obs_mild",
            fontName="Helvetica", fontSize=9, textColor=colors.HexColor("#856404"),
            leading=12, leftIndent=4*mm)

        s["obs_mod"] = ParagraphStyle("obs_mod",
            fontName="Helvetica", fontSize=9, textColor=colors.HexColor("#CA6510"),
            leading=12, leftIndent=4*mm)

        s["obs_notable"] = ParagraphStyle("obs_notable",
            fontName="Helvetica-Bold", fontSize=9, textColor=colors.HexColor("#B02A37"),
            leading=12, leftIndent=4*mm)

        s["metric_label"] = ParagraphStyle("metric_label",
            fontName="Helvetica", fontSize=8, textColor=C_GRAY,
            alignment=TA_LEFT)

        s["metric_value"] = ParagraphStyle("metric_value",
            fontName="Helvetica-Bold", fontSize=10, textColor=C_DARK,
            alignment=TA_LEFT)

        s["disclaimer"] = ParagraphStyle("disclaimer",
            fontName="Helvetica-Oblique", fontSize=7.5, textColor=C_GRAY,
            leading=10, alignment=TA_LEFT)

        return s

    # ── header ────────────────────────────────────────────────────────────────

    def _header(self, styles, patient_id):
        now = datetime.datetime.now().strftime("%d %B %Y, %H:%M")
        return [
            Paragraph("Facial Health Observation Report", styles["title"]),
            Paragraph(f"Patient ID: {patient_id}   |   Generated: {now}   |   "
                      f"System: AI Facial Analysis v1.0", styles["subtitle"]),
        ]

    # ── annotated image ───────────────────────────────────────────────────────

    def _image_section(self, image_bgr, styles):
        rgb  = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        _, png = cv2.imencode(".png", rgb)
        img_io = io.BytesIO(png.tobytes())

        h, w = image_bgr.shape[:2]
        max_w = 100 * mm
        scale = min(max_w / w, (60 * mm) / h)
        rl_img = RLImage(img_io, width=w * scale, height=h * scale)

        return [
            Paragraph("Facial Analysis Visualization", styles["section_head"]),
            rl_img,
            Spacer(1, 2*mm),
            Paragraph(
                "Annotated face mesh with landmark detection and region overlay.",
                styles["body"]
            ),
        ]

    # ── face overview ─────────────────────────────────────────────────────────

    def _face_overview_section(self, p1, face_obs, styles):
        items = [Paragraph("1. Face Overview", styles["section_head"])]

        if p1.success:
            data = [
                ["Metric", "Value", "Metric", "Value"],
                ["Face Width",  f"{p1.face_width} px",
                 "Face Height", f"{p1.face_height} px"],
                ["Symmetry Score", f"{p1.symmetry_score:.1f} / 100",
                 "Symmetry Label", p1.symmetry_label],
                ["Head Tilt", f"{p1.alignment_angle:.1f}°",
                 "Aspect Ratio",
                 f"{(p1.face_height/p1.face_width):.2f}" if p1.face_width else "N/A"],
            ]
            t = Table(data, colWidths=[38*mm, 32*mm, 38*mm, 52*mm])
            t.setStyle(TableStyle([
                ("BACKGROUND",   (0, 0), (-1, 0), C_DARK),
                ("TEXTCOLOR",    (0, 0), (-1, 0), C_WHITE),
                ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",     (0, 0), (-1,-1), 8),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[C_LIGHT, C_WHITE]),
                ("GRID",         (0, 0), (-1,-1), 0.5, colors.HexColor("#CED4DA")),
                ("PADDING",      (0, 0), (-1,-1), 4),
            ]))
            items.append(t)
            items.append(Spacer(1, 3*mm))

        for text in [face_obs.symmetry, face_obs.alignment, face_obs.proportion]:
            if text:
                items.append(Paragraph(f"• {text}", styles["body"]))

        return items

    # ── eye analysis ──────────────────────────────────────────────────────────

    def _eye_section(self, p3, eye_obs, styles):
        items = [Paragraph("2. Eye Analysis", styles["section_head"])]

        # Metrics table
        le, re = p3.left_eye, p3.right_eye
        if le.available or re.available:
            data = [
                ["Feature", "Left Eye", "Right Eye"],
                ["Openness Ratio",
                 f"{le.openness_ratio:.1f}/100" if le.available else "N/A",
                 f"{re.openness_ratio:.1f}/100" if re.available else "N/A"],
                ["Dark Circle Score",
                 f"{le.dark_circle_score:.1f}/100" if le.available else "N/A",
                 f"{re.dark_circle_score:.1f}/100" if re.available else "N/A"],
                ["Redness Score",
                 f"{le.redness_score:.1f}/100" if le.available else "N/A",
                 f"{re.redness_score:.1f}/100" if re.available else "N/A"],
                ["Puffiness Score",
                 f"{le.puffiness_score:.1f}/100" if le.available else "N/A",
                 f"{re.puffiness_score:.1f}/100" if re.available else "N/A"],
            ]
            t = Table(data, colWidths=[60*mm, 50*mm, 50*mm])
            t.setStyle(self._metric_table_style())
            items.append(t)
            items.append(Spacer(1, 3*mm))

        for obs in eye_obs.left + eye_obs.right:
            items.append(Paragraph(f"• {obs.finding}", self._obs_style(styles, obs.severity.value)))
        if eye_obs.openness_note:
            items.append(Paragraph(f"• {eye_obs.openness_note}", styles["body"]))

        return items

    # ── skin analysis ─────────────────────────────────────────────────────────

    def _skin_section(self, p3, skin_obs, styles):
        items = [Paragraph("3. Skin Analysis", styles["section_head"])]

        sf_l = p3.skin_left_cheek
        sf_r = p3.skin_right_cheek
        sf_f = p3.skin_forehead

        if any([sf_f.available, sf_l.available, sf_r.available]):
            def _v(sf, attr):
                return f"{getattr(sf, attr):.1f}" if sf.available else "N/A"

            data = [
                ["Feature", "Forehead", "Left Cheek", "Right Cheek"],
                ["Acne Score", _v(sf_f,"acne_score"),_v(sf_l,"acne_score"),_v(sf_r,"acne_score")],
                ["Redness Score", _v(sf_f,"redness_score"),_v(sf_l,"redness_score"),_v(sf_r,"redness_score")],
                ["Texture Irregularity", _v(sf_f,"texture_irregularity"),_v(sf_l,"texture_irregularity"),_v(sf_r,"texture_irregularity")],
                ["Spot Count", str(sf_f.spot_count) if sf_f.available else "N/A",
                               str(sf_l.spot_count) if sf_l.available else "N/A",
                               str(sf_r.spot_count) if sf_r.available else "N/A"],
            ]
            t = Table(data, colWidths=[50*mm, 40*mm, 40*mm, 40*mm])
            t.setStyle(self._metric_table_style())
            items.append(t)
            items.append(Spacer(1, 3*mm))

        for obs in skin_obs.forehead + skin_obs.left_cheek + skin_obs.right_cheek + skin_obs.overall:
            items.append(Paragraph(f"• {obs.finding}", self._obs_style(styles, obs.severity.value)))

        return items

    # ── lip analysis ──────────────────────────────────────────────────────────

    def _lip_section(self, p3, lip_obs, styles):
        items = [Paragraph("4. Lip Analysis", styles["section_head"])]

        lf = p3.lips
        if lf.available:
            data = [
                ["Feature", "Score (/100)"],
                ["Dryness Score",         f"{lf.dryness_score:.1f}"],
                ["Color Consistency",     f"{lf.color_consistency:.1f}"],
                ["Pallor Score",          f"{lf.pallor_score:.1f}"],
            ]
            t = Table(data, colWidths=[80*mm, 80*mm])
            t.setStyle(self._metric_table_style())
            items.append(t)
            items.append(Spacer(1, 3*mm))

        for obs in lip_obs.findings:
            items.append(Paragraph(f"• {obs.finding}", self._obs_style(styles, obs.severity.value)))

        return items

    # ── overall assessment ────────────────────────────────────────────────────

    def _overall_section(self, p4, styles):
        items = [Paragraph("5. Overall Assessment", styles["section_head"])]

        # Confidence bar
        conf  = p4.overall_confidence
        label = p4.overall_label
        items.append(Paragraph(
            f"<b>Assessment Result:</b> {label}   |   "
            f"<b>Confidence:</b> {conf:.0f}%",
            styles["body"]
        ))
        items.append(Spacer(1, 2*mm))

        for text in p4.overall:
            items.append(Paragraph(f"• {text}", styles["body"]))

        return items

    # ── helpers ───────────────────────────────────────────────────────────────

    def _metric_table_style(self):
        return TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), C_DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), C_WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0, 1), (-1,-1), [C_LIGHT, C_WHITE]),
            ("GRID",          (0, 0), (-1,-1), 0.5, colors.HexColor("#CED4DA")),
            ("PADDING",       (0, 0), (-1,-1), 4),
            ("ALIGN",         (1, 0), (-1,-1), "CENTER"),
        ])

    def _obs_style(self, styles, severity: str):
        sev = severity.lower()
        if sev == "none":     return styles["obs_normal"]
        if sev == "mild":     return styles["obs_mild"]
        if sev == "moderate": return styles["obs_mod"]
        if sev == "notable":  return styles["obs_notable"]
        return styles["body"]
